### ISSUE TITLE
Player teleported into void

### ISSUE THREAD

**Issue by NomiSky** [nerdyjohnny/ovicommunity#12]
Player teleport to a home and ended up in void, was actively dying.

**Comment by NomiSky** [comment]
Issue has happened twice now, staff has been able to teleport player to another player.

**Comment by nerdyjohnny** [comment]
Possible lag issue. RP will be taken offline for now to see if that helps with any system lag

**Comment by nerdyjohnny** [comment]
Ticket 37

**Comment by nerdyjohnny** [comment]
Issue will be marked Unable to Reproduce. I feel it was a server lag issue we were dealing with running two intensive servers at once

**Comment by nerdyjohnny** [comment]
Titrating RAM for servers. Reopen tag unnecessary. 5GB for HCMC, 7 for RP

**Comment by nerdyjohnny** [comment]
No new reports of any lag or issues. Will reopen if issue reoccurs
